# NAS clients veritabanından okunur (sql modülünde read_clients = yes)
# Bu dosya sadece localhost client tanımlar (test için)

client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = localhost
}
